# Generated by Django 5.0 on 2024-01-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_item_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='item',
        ),
    ]
