# Generated by Django 5.0 on 2024-01-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_quantity_orderitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='custumer',
            new_name='customer',
        ),
    ]
