# Generated by Django 5.0 on 2024-01-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
